package main

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"github.com/cobbleopolis/dragoncontimer/ent"
	"github.com/google/uuid"
)

// CreateStation is the resolver for the createStation field.
func (r *mutationResolver) CreateStation(ctx context.Context, input ent.CreateStationInput) (*ent.Station, error) {
	client := ent.FromContext(ctx)
	return client.Station.Create().SetInput(input).Save(ctx)
	// panic(fmt.Errorf("not implemented: CreateStation - createStation"))
}

// UpdateStation is the resolver for the updateStation field.
func (r *mutationResolver) UpdateStation(ctx context.Context, id uuid.UUID, input ent.UpdateStationInput) (*ent.Station, error) {
	client := ent.FromContext(ctx)
	return client.Station.UpdateOneID(id).SetInput(input).Save(ctx)
	// panic(fmt.Errorf("not implemented: UpdateStation - updateStation"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
