package main

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"entgo.io/contrib/entgql"
	"github.com/cobbleopolis/dragoncontimer/ent"
	"github.com/google/uuid"
)

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id uuid.UUID) (ent.Noder, error) {
	return r.client.Noder(ctx, id)
	// panic(fmt.Errorf("not implemented: Node - node"))
}

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(ctx context.Context, ids []uuid.UUID) ([]ent.Noder, error) {
	return r.client.Noders(ctx, ids)
	// panic(fmt.Errorf("not implemented: Nodes - nodes"))
}

// Stations is the resolver for the stations field.
func (r *queryResolver) Stations(ctx context.Context, after *entgql.Cursor[uuid.UUID], first *int, before *entgql.Cursor[uuid.UUID], last *int, orderBy *ent.StationOrder, where *ent.StationWhereInput) (*ent.StationConnection, error) {
	return r.client.Station.
		Query().
		Paginate(
			ctx,
			after,
			first,
			before,
			last,
			ent.WithStationOrder(orderBy),
			ent.WithStationFilter(where.Filter),
		)
	// panic(fmt.Errorf("not implemented: Stations - stations"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
