// Code generated by ent, DO NOT EDIT.

package station

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the station type in the database.
	Label = "station"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCheckoutTime holds the string denoting the checkouttime field in the database.
	FieldCheckoutTime = "checkout_time"
	// FieldCurrentPlayer holds the string denoting the currentplayer field in the database.
	FieldCurrentPlayer = "current_player"
	// Table holds the table name of the station in the database.
	Table = "stations"
)

// Columns holds all SQL columns for station fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldStatus,
	FieldCheckoutTime,
	FieldCurrentPlayer,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// Status values.
const (
	StatusDEFAULT       Status = "DEFAULT"
	StatusCHECKED_OUT   Status = "CHECKED_OUT"
	StatusNOT_AVAILABLE Status = "NOT_AVAILABLE"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusDEFAULT, StatusCHECKED_OUT, StatusNOT_AVAILABLE:
		return nil
	default:
		return fmt.Errorf("station: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Station queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCheckoutTime orders the results by the checkoutTime field.
func ByCheckoutTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCheckoutTime, opts...).ToFunc()
}

// ByCurrentPlayer orders the results by the currentPlayer field.
func ByCurrentPlayer(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentPlayer, opts...).ToFunc()
}
