// Code generated by ent, DO NOT EDIT.

package station

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/cobbleopolis/dragoncontimer/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Station {
	return predicate.Station(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Station {
	return predicate.Station(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Station {
	return predicate.Station(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Station {
	return predicate.Station(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Station {
	return predicate.Station(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Station {
	return predicate.Station(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Station {
	return predicate.Station(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Station {
	return predicate.Station(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Station {
	return predicate.Station(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Station {
	return predicate.Station(sql.FieldEQ(FieldName, v))
}

// CheckoutTime applies equality check predicate on the "checkoutTime" field. It's identical to CheckoutTimeEQ.
func CheckoutTime(v time.Time) predicate.Station {
	return predicate.Station(sql.FieldEQ(FieldCheckoutTime, v))
}

// CurrentPlayer applies equality check predicate on the "currentPlayer" field. It's identical to CurrentPlayerEQ.
func CurrentPlayer(v string) predicate.Station {
	return predicate.Station(sql.FieldEQ(FieldCurrentPlayer, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Station {
	return predicate.Station(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Station {
	return predicate.Station(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Station {
	return predicate.Station(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Station {
	return predicate.Station(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Station {
	return predicate.Station(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Station {
	return predicate.Station(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Station {
	return predicate.Station(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Station {
	return predicate.Station(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Station {
	return predicate.Station(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Station {
	return predicate.Station(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Station {
	return predicate.Station(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Station {
	return predicate.Station(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Station {
	return predicate.Station(sql.FieldContainsFold(FieldName, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Station {
	return predicate.Station(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Station {
	return predicate.Station(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Station {
	return predicate.Station(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Station {
	return predicate.Station(sql.FieldNotIn(FieldStatus, vs...))
}

// CheckoutTimeEQ applies the EQ predicate on the "checkoutTime" field.
func CheckoutTimeEQ(v time.Time) predicate.Station {
	return predicate.Station(sql.FieldEQ(FieldCheckoutTime, v))
}

// CheckoutTimeNEQ applies the NEQ predicate on the "checkoutTime" field.
func CheckoutTimeNEQ(v time.Time) predicate.Station {
	return predicate.Station(sql.FieldNEQ(FieldCheckoutTime, v))
}

// CheckoutTimeIn applies the In predicate on the "checkoutTime" field.
func CheckoutTimeIn(vs ...time.Time) predicate.Station {
	return predicate.Station(sql.FieldIn(FieldCheckoutTime, vs...))
}

// CheckoutTimeNotIn applies the NotIn predicate on the "checkoutTime" field.
func CheckoutTimeNotIn(vs ...time.Time) predicate.Station {
	return predicate.Station(sql.FieldNotIn(FieldCheckoutTime, vs...))
}

// CheckoutTimeGT applies the GT predicate on the "checkoutTime" field.
func CheckoutTimeGT(v time.Time) predicate.Station {
	return predicate.Station(sql.FieldGT(FieldCheckoutTime, v))
}

// CheckoutTimeGTE applies the GTE predicate on the "checkoutTime" field.
func CheckoutTimeGTE(v time.Time) predicate.Station {
	return predicate.Station(sql.FieldGTE(FieldCheckoutTime, v))
}

// CheckoutTimeLT applies the LT predicate on the "checkoutTime" field.
func CheckoutTimeLT(v time.Time) predicate.Station {
	return predicate.Station(sql.FieldLT(FieldCheckoutTime, v))
}

// CheckoutTimeLTE applies the LTE predicate on the "checkoutTime" field.
func CheckoutTimeLTE(v time.Time) predicate.Station {
	return predicate.Station(sql.FieldLTE(FieldCheckoutTime, v))
}

// CheckoutTimeIsNil applies the IsNil predicate on the "checkoutTime" field.
func CheckoutTimeIsNil() predicate.Station {
	return predicate.Station(sql.FieldIsNull(FieldCheckoutTime))
}

// CheckoutTimeNotNil applies the NotNil predicate on the "checkoutTime" field.
func CheckoutTimeNotNil() predicate.Station {
	return predicate.Station(sql.FieldNotNull(FieldCheckoutTime))
}

// CurrentPlayerEQ applies the EQ predicate on the "currentPlayer" field.
func CurrentPlayerEQ(v string) predicate.Station {
	return predicate.Station(sql.FieldEQ(FieldCurrentPlayer, v))
}

// CurrentPlayerNEQ applies the NEQ predicate on the "currentPlayer" field.
func CurrentPlayerNEQ(v string) predicate.Station {
	return predicate.Station(sql.FieldNEQ(FieldCurrentPlayer, v))
}

// CurrentPlayerIn applies the In predicate on the "currentPlayer" field.
func CurrentPlayerIn(vs ...string) predicate.Station {
	return predicate.Station(sql.FieldIn(FieldCurrentPlayer, vs...))
}

// CurrentPlayerNotIn applies the NotIn predicate on the "currentPlayer" field.
func CurrentPlayerNotIn(vs ...string) predicate.Station {
	return predicate.Station(sql.FieldNotIn(FieldCurrentPlayer, vs...))
}

// CurrentPlayerGT applies the GT predicate on the "currentPlayer" field.
func CurrentPlayerGT(v string) predicate.Station {
	return predicate.Station(sql.FieldGT(FieldCurrentPlayer, v))
}

// CurrentPlayerGTE applies the GTE predicate on the "currentPlayer" field.
func CurrentPlayerGTE(v string) predicate.Station {
	return predicate.Station(sql.FieldGTE(FieldCurrentPlayer, v))
}

// CurrentPlayerLT applies the LT predicate on the "currentPlayer" field.
func CurrentPlayerLT(v string) predicate.Station {
	return predicate.Station(sql.FieldLT(FieldCurrentPlayer, v))
}

// CurrentPlayerLTE applies the LTE predicate on the "currentPlayer" field.
func CurrentPlayerLTE(v string) predicate.Station {
	return predicate.Station(sql.FieldLTE(FieldCurrentPlayer, v))
}

// CurrentPlayerContains applies the Contains predicate on the "currentPlayer" field.
func CurrentPlayerContains(v string) predicate.Station {
	return predicate.Station(sql.FieldContains(FieldCurrentPlayer, v))
}

// CurrentPlayerHasPrefix applies the HasPrefix predicate on the "currentPlayer" field.
func CurrentPlayerHasPrefix(v string) predicate.Station {
	return predicate.Station(sql.FieldHasPrefix(FieldCurrentPlayer, v))
}

// CurrentPlayerHasSuffix applies the HasSuffix predicate on the "currentPlayer" field.
func CurrentPlayerHasSuffix(v string) predicate.Station {
	return predicate.Station(sql.FieldHasSuffix(FieldCurrentPlayer, v))
}

// CurrentPlayerIsNil applies the IsNil predicate on the "currentPlayer" field.
func CurrentPlayerIsNil() predicate.Station {
	return predicate.Station(sql.FieldIsNull(FieldCurrentPlayer))
}

// CurrentPlayerNotNil applies the NotNil predicate on the "currentPlayer" field.
func CurrentPlayerNotNil() predicate.Station {
	return predicate.Station(sql.FieldNotNull(FieldCurrentPlayer))
}

// CurrentPlayerEqualFold applies the EqualFold predicate on the "currentPlayer" field.
func CurrentPlayerEqualFold(v string) predicate.Station {
	return predicate.Station(sql.FieldEqualFold(FieldCurrentPlayer, v))
}

// CurrentPlayerContainsFold applies the ContainsFold predicate on the "currentPlayer" field.
func CurrentPlayerContainsFold(v string) predicate.Station {
	return predicate.Station(sql.FieldContainsFold(FieldCurrentPlayer, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Station) predicate.Station {
	return predicate.Station(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Station) predicate.Station {
	return predicate.Station(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Station) predicate.Station {
	return predicate.Station(sql.NotPredicates(p))
}
