// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/cobbleopolis/dragoncontimer/ent/station"
)

// CreateStationInput represents a mutation input for creating stations.
type CreateStationInput struct {
	Name          string
	Status        *station.Status
	CheckoutTime  *time.Time
	CurrentPlayer *string
	OrderPriority *int
}

// Mutate applies the CreateStationInput on the StationMutation builder.
func (i *CreateStationInput) Mutate(m *StationMutation) {
	m.SetName(i.Name)
	if v := i.Status; v != nil {
		m.SetStatus(*v)
	}
	if v := i.CheckoutTime; v != nil {
		m.SetCheckoutTime(*v)
	}
	if v := i.CurrentPlayer; v != nil {
		m.SetCurrentPlayer(*v)
	}
	if v := i.OrderPriority; v != nil {
		m.SetOrderPriority(*v)
	}
}

// SetInput applies the change-set in the CreateStationInput on the StationCreate builder.
func (c *StationCreate) SetInput(i CreateStationInput) *StationCreate {
	i.Mutate(c.Mutation())
	return c
}

// UpdateStationInput represents a mutation input for updating stations.
type UpdateStationInput struct {
	Name               *string
	Status             *station.Status
	ClearCheckoutTime  bool
	CheckoutTime       *time.Time
	ClearCurrentPlayer bool
	CurrentPlayer      *string
	OrderPriority      *int
}

// Mutate applies the UpdateStationInput on the StationMutation builder.
func (i *UpdateStationInput) Mutate(m *StationMutation) {
	if v := i.Name; v != nil {
		m.SetName(*v)
	}
	if v := i.Status; v != nil {
		m.SetStatus(*v)
	}
	if i.ClearCheckoutTime {
		m.ClearCheckoutTime()
	}
	if v := i.CheckoutTime; v != nil {
		m.SetCheckoutTime(*v)
	}
	if i.ClearCurrentPlayer {
		m.ClearCurrentPlayer()
	}
	if v := i.CurrentPlayer; v != nil {
		m.SetCurrentPlayer(*v)
	}
	if v := i.OrderPriority; v != nil {
		m.SetOrderPriority(*v)
	}
}

// SetInput applies the change-set in the UpdateStationInput on the StationUpdate builder.
func (c *StationUpdate) SetInput(i UpdateStationInput) *StationUpdate {
	i.Mutate(c.Mutation())
	return c
}

// SetInput applies the change-set in the UpdateStationInput on the StationUpdateOne builder.
func (c *StationUpdateOne) SetInput(i UpdateStationInput) *StationUpdateOne {
	i.Mutate(c.Mutation())
	return c
}
