// Code generated by ent, DO NOT EDIT.

package ent

import (
	"errors"
	"fmt"
	"time"

	"github.com/cobbleopolis/dragoncontimer/ent/predicate"
	"github.com/cobbleopolis/dragoncontimer/ent/project"
	"github.com/cobbleopolis/dragoncontimer/ent/station"
	"github.com/google/uuid"
)

// ProjectWhereInput represents a where input for filtering Project queries.
type ProjectWhereInput struct {
	Predicates []predicate.Project  `json:"-"`
	Not        *ProjectWhereInput   `json:"not,omitempty"`
	Or         []*ProjectWhereInput `json:"or,omitempty"`
	And        []*ProjectWhereInput `json:"and,omitempty"`

	// "id" field predicates.
	ID      *uuid.UUID  `json:"id,omitempty"`
	IDNEQ   *uuid.UUID  `json:"idNEQ,omitempty"`
	IDIn    []uuid.UUID `json:"idIn,omitempty"`
	IDNotIn []uuid.UUID `json:"idNotIn,omitempty"`
	IDGT    *uuid.UUID  `json:"idGT,omitempty"`
	IDGTE   *uuid.UUID  `json:"idGTE,omitempty"`
	IDLT    *uuid.UUID  `json:"idLT,omitempty"`
	IDLTE   *uuid.UUID  `json:"idLTE,omitempty"`
}

// AddPredicates adds custom predicates to the where input to be used during the filtering phase.
func (i *ProjectWhereInput) AddPredicates(predicates ...predicate.Project) {
	i.Predicates = append(i.Predicates, predicates...)
}

// Filter applies the ProjectWhereInput filter on the ProjectQuery builder.
func (i *ProjectWhereInput) Filter(q *ProjectQuery) (*ProjectQuery, error) {
	if i == nil {
		return q, nil
	}
	p, err := i.P()
	if err != nil {
		if err == ErrEmptyProjectWhereInput {
			return q, nil
		}
		return nil, err
	}
	return q.Where(p), nil
}

// ErrEmptyProjectWhereInput is returned in case the ProjectWhereInput is empty.
var ErrEmptyProjectWhereInput = errors.New("ent: empty predicate ProjectWhereInput")

// P returns a predicate for filtering projects.
// An error is returned if the input is empty or invalid.
func (i *ProjectWhereInput) P() (predicate.Project, error) {
	var predicates []predicate.Project
	if i.Not != nil {
		p, err := i.Not.P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'not'", err)
		}
		predicates = append(predicates, project.Not(p))
	}
	switch n := len(i.Or); {
	case n == 1:
		p, err := i.Or[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'or'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		or := make([]predicate.Project, 0, n)
		for _, w := range i.Or {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'or'", err)
			}
			or = append(or, p)
		}
		predicates = append(predicates, project.Or(or...))
	}
	switch n := len(i.And); {
	case n == 1:
		p, err := i.And[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'and'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		and := make([]predicate.Project, 0, n)
		for _, w := range i.And {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'and'", err)
			}
			and = append(and, p)
		}
		predicates = append(predicates, project.And(and...))
	}
	predicates = append(predicates, i.Predicates...)
	if i.ID != nil {
		predicates = append(predicates, project.IDEQ(*i.ID))
	}
	if i.IDNEQ != nil {
		predicates = append(predicates, project.IDNEQ(*i.IDNEQ))
	}
	if len(i.IDIn) > 0 {
		predicates = append(predicates, project.IDIn(i.IDIn...))
	}
	if len(i.IDNotIn) > 0 {
		predicates = append(predicates, project.IDNotIn(i.IDNotIn...))
	}
	if i.IDGT != nil {
		predicates = append(predicates, project.IDGT(*i.IDGT))
	}
	if i.IDGTE != nil {
		predicates = append(predicates, project.IDGTE(*i.IDGTE))
	}
	if i.IDLT != nil {
		predicates = append(predicates, project.IDLT(*i.IDLT))
	}
	if i.IDLTE != nil {
		predicates = append(predicates, project.IDLTE(*i.IDLTE))
	}

	switch len(predicates) {
	case 0:
		return nil, ErrEmptyProjectWhereInput
	case 1:
		return predicates[0], nil
	default:
		return project.And(predicates...), nil
	}
}

// StationWhereInput represents a where input for filtering Station queries.
type StationWhereInput struct {
	Predicates []predicate.Station  `json:"-"`
	Not        *StationWhereInput   `json:"not,omitempty"`
	Or         []*StationWhereInput `json:"or,omitempty"`
	And        []*StationWhereInput `json:"and,omitempty"`

	// "id" field predicates.
	ID      *uuid.UUID  `json:"id,omitempty"`
	IDNEQ   *uuid.UUID  `json:"idNEQ,omitempty"`
	IDIn    []uuid.UUID `json:"idIn,omitempty"`
	IDNotIn []uuid.UUID `json:"idNotIn,omitempty"`
	IDGT    *uuid.UUID  `json:"idGT,omitempty"`
	IDGTE   *uuid.UUID  `json:"idGTE,omitempty"`
	IDLT    *uuid.UUID  `json:"idLT,omitempty"`
	IDLTE   *uuid.UUID  `json:"idLTE,omitempty"`

	// "name" field predicates.
	Name             *string  `json:"name,omitempty"`
	NameNEQ          *string  `json:"nameNEQ,omitempty"`
	NameIn           []string `json:"nameIn,omitempty"`
	NameNotIn        []string `json:"nameNotIn,omitempty"`
	NameGT           *string  `json:"nameGT,omitempty"`
	NameGTE          *string  `json:"nameGTE,omitempty"`
	NameLT           *string  `json:"nameLT,omitempty"`
	NameLTE          *string  `json:"nameLTE,omitempty"`
	NameContains     *string  `json:"nameContains,omitempty"`
	NameHasPrefix    *string  `json:"nameHasPrefix,omitempty"`
	NameHasSuffix    *string  `json:"nameHasSuffix,omitempty"`
	NameEqualFold    *string  `json:"nameEqualFold,omitempty"`
	NameContainsFold *string  `json:"nameContainsFold,omitempty"`

	// "status" field predicates.
	Status      *station.Status  `json:"status,omitempty"`
	StatusNEQ   *station.Status  `json:"statusNEQ,omitempty"`
	StatusIn    []station.Status `json:"statusIn,omitempty"`
	StatusNotIn []station.Status `json:"statusNotIn,omitempty"`

	// "checkoutTime" field predicates.
	CheckoutTime       *time.Time  `json:"checkouttime,omitempty"`
	CheckoutTimeNEQ    *time.Time  `json:"checkouttimeNEQ,omitempty"`
	CheckoutTimeIn     []time.Time `json:"checkouttimeIn,omitempty"`
	CheckoutTimeNotIn  []time.Time `json:"checkouttimeNotIn,omitempty"`
	CheckoutTimeGT     *time.Time  `json:"checkouttimeGT,omitempty"`
	CheckoutTimeGTE    *time.Time  `json:"checkouttimeGTE,omitempty"`
	CheckoutTimeLT     *time.Time  `json:"checkouttimeLT,omitempty"`
	CheckoutTimeLTE    *time.Time  `json:"checkouttimeLTE,omitempty"`
	CheckoutTimeIsNil  bool        `json:"checkouttimeIsNil,omitempty"`
	CheckoutTimeNotNil bool        `json:"checkouttimeNotNil,omitempty"`

	// "currentPlayer" field predicates.
	CurrentPlayer             *string  `json:"currentplayer,omitempty"`
	CurrentPlayerNEQ          *string  `json:"currentplayerNEQ,omitempty"`
	CurrentPlayerIn           []string `json:"currentplayerIn,omitempty"`
	CurrentPlayerNotIn        []string `json:"currentplayerNotIn,omitempty"`
	CurrentPlayerGT           *string  `json:"currentplayerGT,omitempty"`
	CurrentPlayerGTE          *string  `json:"currentplayerGTE,omitempty"`
	CurrentPlayerLT           *string  `json:"currentplayerLT,omitempty"`
	CurrentPlayerLTE          *string  `json:"currentplayerLTE,omitempty"`
	CurrentPlayerContains     *string  `json:"currentplayerContains,omitempty"`
	CurrentPlayerHasPrefix    *string  `json:"currentplayerHasPrefix,omitempty"`
	CurrentPlayerHasSuffix    *string  `json:"currentplayerHasSuffix,omitempty"`
	CurrentPlayerIsNil        bool     `json:"currentplayerIsNil,omitempty"`
	CurrentPlayerNotNil       bool     `json:"currentplayerNotNil,omitempty"`
	CurrentPlayerEqualFold    *string  `json:"currentplayerEqualFold,omitempty"`
	CurrentPlayerContainsFold *string  `json:"currentplayerContainsFold,omitempty"`

	// "orderPriority" field predicates.
	OrderPriority      *int  `json:"orderpriority,omitempty"`
	OrderPriorityNEQ   *int  `json:"orderpriorityNEQ,omitempty"`
	OrderPriorityIn    []int `json:"orderpriorityIn,omitempty"`
	OrderPriorityNotIn []int `json:"orderpriorityNotIn,omitempty"`
	OrderPriorityGT    *int  `json:"orderpriorityGT,omitempty"`
	OrderPriorityGTE   *int  `json:"orderpriorityGTE,omitempty"`
	OrderPriorityLT    *int  `json:"orderpriorityLT,omitempty"`
	OrderPriorityLTE   *int  `json:"orderpriorityLTE,omitempty"`
}

// AddPredicates adds custom predicates to the where input to be used during the filtering phase.
func (i *StationWhereInput) AddPredicates(predicates ...predicate.Station) {
	i.Predicates = append(i.Predicates, predicates...)
}

// Filter applies the StationWhereInput filter on the StationQuery builder.
func (i *StationWhereInput) Filter(q *StationQuery) (*StationQuery, error) {
	if i == nil {
		return q, nil
	}
	p, err := i.P()
	if err != nil {
		if err == ErrEmptyStationWhereInput {
			return q, nil
		}
		return nil, err
	}
	return q.Where(p), nil
}

// ErrEmptyStationWhereInput is returned in case the StationWhereInput is empty.
var ErrEmptyStationWhereInput = errors.New("ent: empty predicate StationWhereInput")

// P returns a predicate for filtering stations.
// An error is returned if the input is empty or invalid.
func (i *StationWhereInput) P() (predicate.Station, error) {
	var predicates []predicate.Station
	if i.Not != nil {
		p, err := i.Not.P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'not'", err)
		}
		predicates = append(predicates, station.Not(p))
	}
	switch n := len(i.Or); {
	case n == 1:
		p, err := i.Or[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'or'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		or := make([]predicate.Station, 0, n)
		for _, w := range i.Or {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'or'", err)
			}
			or = append(or, p)
		}
		predicates = append(predicates, station.Or(or...))
	}
	switch n := len(i.And); {
	case n == 1:
		p, err := i.And[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'and'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		and := make([]predicate.Station, 0, n)
		for _, w := range i.And {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'and'", err)
			}
			and = append(and, p)
		}
		predicates = append(predicates, station.And(and...))
	}
	predicates = append(predicates, i.Predicates...)
	if i.ID != nil {
		predicates = append(predicates, station.IDEQ(*i.ID))
	}
	if i.IDNEQ != nil {
		predicates = append(predicates, station.IDNEQ(*i.IDNEQ))
	}
	if len(i.IDIn) > 0 {
		predicates = append(predicates, station.IDIn(i.IDIn...))
	}
	if len(i.IDNotIn) > 0 {
		predicates = append(predicates, station.IDNotIn(i.IDNotIn...))
	}
	if i.IDGT != nil {
		predicates = append(predicates, station.IDGT(*i.IDGT))
	}
	if i.IDGTE != nil {
		predicates = append(predicates, station.IDGTE(*i.IDGTE))
	}
	if i.IDLT != nil {
		predicates = append(predicates, station.IDLT(*i.IDLT))
	}
	if i.IDLTE != nil {
		predicates = append(predicates, station.IDLTE(*i.IDLTE))
	}
	if i.Name != nil {
		predicates = append(predicates, station.NameEQ(*i.Name))
	}
	if i.NameNEQ != nil {
		predicates = append(predicates, station.NameNEQ(*i.NameNEQ))
	}
	if len(i.NameIn) > 0 {
		predicates = append(predicates, station.NameIn(i.NameIn...))
	}
	if len(i.NameNotIn) > 0 {
		predicates = append(predicates, station.NameNotIn(i.NameNotIn...))
	}
	if i.NameGT != nil {
		predicates = append(predicates, station.NameGT(*i.NameGT))
	}
	if i.NameGTE != nil {
		predicates = append(predicates, station.NameGTE(*i.NameGTE))
	}
	if i.NameLT != nil {
		predicates = append(predicates, station.NameLT(*i.NameLT))
	}
	if i.NameLTE != nil {
		predicates = append(predicates, station.NameLTE(*i.NameLTE))
	}
	if i.NameContains != nil {
		predicates = append(predicates, station.NameContains(*i.NameContains))
	}
	if i.NameHasPrefix != nil {
		predicates = append(predicates, station.NameHasPrefix(*i.NameHasPrefix))
	}
	if i.NameHasSuffix != nil {
		predicates = append(predicates, station.NameHasSuffix(*i.NameHasSuffix))
	}
	if i.NameEqualFold != nil {
		predicates = append(predicates, station.NameEqualFold(*i.NameEqualFold))
	}
	if i.NameContainsFold != nil {
		predicates = append(predicates, station.NameContainsFold(*i.NameContainsFold))
	}
	if i.Status != nil {
		predicates = append(predicates, station.StatusEQ(*i.Status))
	}
	if i.StatusNEQ != nil {
		predicates = append(predicates, station.StatusNEQ(*i.StatusNEQ))
	}
	if len(i.StatusIn) > 0 {
		predicates = append(predicates, station.StatusIn(i.StatusIn...))
	}
	if len(i.StatusNotIn) > 0 {
		predicates = append(predicates, station.StatusNotIn(i.StatusNotIn...))
	}
	if i.CheckoutTime != nil {
		predicates = append(predicates, station.CheckoutTimeEQ(*i.CheckoutTime))
	}
	if i.CheckoutTimeNEQ != nil {
		predicates = append(predicates, station.CheckoutTimeNEQ(*i.CheckoutTimeNEQ))
	}
	if len(i.CheckoutTimeIn) > 0 {
		predicates = append(predicates, station.CheckoutTimeIn(i.CheckoutTimeIn...))
	}
	if len(i.CheckoutTimeNotIn) > 0 {
		predicates = append(predicates, station.CheckoutTimeNotIn(i.CheckoutTimeNotIn...))
	}
	if i.CheckoutTimeGT != nil {
		predicates = append(predicates, station.CheckoutTimeGT(*i.CheckoutTimeGT))
	}
	if i.CheckoutTimeGTE != nil {
		predicates = append(predicates, station.CheckoutTimeGTE(*i.CheckoutTimeGTE))
	}
	if i.CheckoutTimeLT != nil {
		predicates = append(predicates, station.CheckoutTimeLT(*i.CheckoutTimeLT))
	}
	if i.CheckoutTimeLTE != nil {
		predicates = append(predicates, station.CheckoutTimeLTE(*i.CheckoutTimeLTE))
	}
	if i.CheckoutTimeIsNil {
		predicates = append(predicates, station.CheckoutTimeIsNil())
	}
	if i.CheckoutTimeNotNil {
		predicates = append(predicates, station.CheckoutTimeNotNil())
	}
	if i.CurrentPlayer != nil {
		predicates = append(predicates, station.CurrentPlayerEQ(*i.CurrentPlayer))
	}
	if i.CurrentPlayerNEQ != nil {
		predicates = append(predicates, station.CurrentPlayerNEQ(*i.CurrentPlayerNEQ))
	}
	if len(i.CurrentPlayerIn) > 0 {
		predicates = append(predicates, station.CurrentPlayerIn(i.CurrentPlayerIn...))
	}
	if len(i.CurrentPlayerNotIn) > 0 {
		predicates = append(predicates, station.CurrentPlayerNotIn(i.CurrentPlayerNotIn...))
	}
	if i.CurrentPlayerGT != nil {
		predicates = append(predicates, station.CurrentPlayerGT(*i.CurrentPlayerGT))
	}
	if i.CurrentPlayerGTE != nil {
		predicates = append(predicates, station.CurrentPlayerGTE(*i.CurrentPlayerGTE))
	}
	if i.CurrentPlayerLT != nil {
		predicates = append(predicates, station.CurrentPlayerLT(*i.CurrentPlayerLT))
	}
	if i.CurrentPlayerLTE != nil {
		predicates = append(predicates, station.CurrentPlayerLTE(*i.CurrentPlayerLTE))
	}
	if i.CurrentPlayerContains != nil {
		predicates = append(predicates, station.CurrentPlayerContains(*i.CurrentPlayerContains))
	}
	if i.CurrentPlayerHasPrefix != nil {
		predicates = append(predicates, station.CurrentPlayerHasPrefix(*i.CurrentPlayerHasPrefix))
	}
	if i.CurrentPlayerHasSuffix != nil {
		predicates = append(predicates, station.CurrentPlayerHasSuffix(*i.CurrentPlayerHasSuffix))
	}
	if i.CurrentPlayerIsNil {
		predicates = append(predicates, station.CurrentPlayerIsNil())
	}
	if i.CurrentPlayerNotNil {
		predicates = append(predicates, station.CurrentPlayerNotNil())
	}
	if i.CurrentPlayerEqualFold != nil {
		predicates = append(predicates, station.CurrentPlayerEqualFold(*i.CurrentPlayerEqualFold))
	}
	if i.CurrentPlayerContainsFold != nil {
		predicates = append(predicates, station.CurrentPlayerContainsFold(*i.CurrentPlayerContainsFold))
	}
	if i.OrderPriority != nil {
		predicates = append(predicates, station.OrderPriorityEQ(*i.OrderPriority))
	}
	if i.OrderPriorityNEQ != nil {
		predicates = append(predicates, station.OrderPriorityNEQ(*i.OrderPriorityNEQ))
	}
	if len(i.OrderPriorityIn) > 0 {
		predicates = append(predicates, station.OrderPriorityIn(i.OrderPriorityIn...))
	}
	if len(i.OrderPriorityNotIn) > 0 {
		predicates = append(predicates, station.OrderPriorityNotIn(i.OrderPriorityNotIn...))
	}
	if i.OrderPriorityGT != nil {
		predicates = append(predicates, station.OrderPriorityGT(*i.OrderPriorityGT))
	}
	if i.OrderPriorityGTE != nil {
		predicates = append(predicates, station.OrderPriorityGTE(*i.OrderPriorityGTE))
	}
	if i.OrderPriorityLT != nil {
		predicates = append(predicates, station.OrderPriorityLT(*i.OrderPriorityLT))
	}
	if i.OrderPriorityLTE != nil {
		predicates = append(predicates, station.OrderPriorityLTE(*i.OrderPriorityLTE))
	}

	switch len(predicates) {
	case 0:
		return nil, ErrEmptyStationWhereInput
	case 1:
		return predicates[0], nil
	default:
		return station.And(predicates...), nil
	}
}
