// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/cobbleopolis/dragoncontimer/ent/predicate"
	"github.com/cobbleopolis/dragoncontimer/ent/station"
	"github.com/google/uuid"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeStation = "Station"
)

// StationMutation represents an operation that mutates the Station nodes in the graph.
type StationMutation struct {
	config
	op            Op
	typ           string
	id            *uuid.UUID
	name          *string
	status        *station.Status
	checkoutTime  *time.Time
	currentPlayer *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Station, error)
	predicates    []predicate.Station
}

var _ ent.Mutation = (*StationMutation)(nil)

// stationOption allows management of the mutation configuration using functional options.
type stationOption func(*StationMutation)

// newStationMutation creates new mutation for the Station entity.
func newStationMutation(c config, op Op, opts ...stationOption) *StationMutation {
	m := &StationMutation{
		config:        c,
		op:            op,
		typ:           TypeStation,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withStationID sets the ID field of the mutation.
func withStationID(id uuid.UUID) stationOption {
	return func(m *StationMutation) {
		var (
			err   error
			once  sync.Once
			value *Station
		)
		m.oldValue = func(ctx context.Context) (*Station, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Station.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withStation sets the old Station of the mutation.
func withStation(node *Station) stationOption {
	return func(m *StationMutation) {
		m.oldValue = func(context.Context) (*Station, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m StationMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m StationMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Station entities.
func (m *StationMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *StationMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *StationMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Station.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *StationMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *StationMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Station entity.
// If the Station object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StationMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *StationMutation) ResetName() {
	m.name = nil
}

// SetStatus sets the "status" field.
func (m *StationMutation) SetStatus(s station.Status) {
	m.status = &s
}

// Status returns the value of the "status" field in the mutation.
func (m *StationMutation) Status() (r station.Status, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the Station entity.
// If the Station object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StationMutation) OldStatus(ctx context.Context) (v station.Status, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *StationMutation) ResetStatus() {
	m.status = nil
}

// SetCheckoutTime sets the "checkoutTime" field.
func (m *StationMutation) SetCheckoutTime(t time.Time) {
	m.checkoutTime = &t
}

// CheckoutTime returns the value of the "checkoutTime" field in the mutation.
func (m *StationMutation) CheckoutTime() (r time.Time, exists bool) {
	v := m.checkoutTime
	if v == nil {
		return
	}
	return *v, true
}

// OldCheckoutTime returns the old "checkoutTime" field's value of the Station entity.
// If the Station object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StationMutation) OldCheckoutTime(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCheckoutTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCheckoutTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCheckoutTime: %w", err)
	}
	return oldValue.CheckoutTime, nil
}

// ClearCheckoutTime clears the value of the "checkoutTime" field.
func (m *StationMutation) ClearCheckoutTime() {
	m.checkoutTime = nil
	m.clearedFields[station.FieldCheckoutTime] = struct{}{}
}

// CheckoutTimeCleared returns if the "checkoutTime" field was cleared in this mutation.
func (m *StationMutation) CheckoutTimeCleared() bool {
	_, ok := m.clearedFields[station.FieldCheckoutTime]
	return ok
}

// ResetCheckoutTime resets all changes to the "checkoutTime" field.
func (m *StationMutation) ResetCheckoutTime() {
	m.checkoutTime = nil
	delete(m.clearedFields, station.FieldCheckoutTime)
}

// SetCurrentPlayer sets the "currentPlayer" field.
func (m *StationMutation) SetCurrentPlayer(s string) {
	m.currentPlayer = &s
}

// CurrentPlayer returns the value of the "currentPlayer" field in the mutation.
func (m *StationMutation) CurrentPlayer() (r string, exists bool) {
	v := m.currentPlayer
	if v == nil {
		return
	}
	return *v, true
}

// OldCurrentPlayer returns the old "currentPlayer" field's value of the Station entity.
// If the Station object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StationMutation) OldCurrentPlayer(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCurrentPlayer is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCurrentPlayer requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCurrentPlayer: %w", err)
	}
	return oldValue.CurrentPlayer, nil
}

// ClearCurrentPlayer clears the value of the "currentPlayer" field.
func (m *StationMutation) ClearCurrentPlayer() {
	m.currentPlayer = nil
	m.clearedFields[station.FieldCurrentPlayer] = struct{}{}
}

// CurrentPlayerCleared returns if the "currentPlayer" field was cleared in this mutation.
func (m *StationMutation) CurrentPlayerCleared() bool {
	_, ok := m.clearedFields[station.FieldCurrentPlayer]
	return ok
}

// ResetCurrentPlayer resets all changes to the "currentPlayer" field.
func (m *StationMutation) ResetCurrentPlayer() {
	m.currentPlayer = nil
	delete(m.clearedFields, station.FieldCurrentPlayer)
}

// Where appends a list predicates to the StationMutation builder.
func (m *StationMutation) Where(ps ...predicate.Station) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the StationMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *StationMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Station, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *StationMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *StationMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Station).
func (m *StationMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *StationMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.name != nil {
		fields = append(fields, station.FieldName)
	}
	if m.status != nil {
		fields = append(fields, station.FieldStatus)
	}
	if m.checkoutTime != nil {
		fields = append(fields, station.FieldCheckoutTime)
	}
	if m.currentPlayer != nil {
		fields = append(fields, station.FieldCurrentPlayer)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *StationMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case station.FieldName:
		return m.Name()
	case station.FieldStatus:
		return m.Status()
	case station.FieldCheckoutTime:
		return m.CheckoutTime()
	case station.FieldCurrentPlayer:
		return m.CurrentPlayer()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *StationMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case station.FieldName:
		return m.OldName(ctx)
	case station.FieldStatus:
		return m.OldStatus(ctx)
	case station.FieldCheckoutTime:
		return m.OldCheckoutTime(ctx)
	case station.FieldCurrentPlayer:
		return m.OldCurrentPlayer(ctx)
	}
	return nil, fmt.Errorf("unknown Station field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *StationMutation) SetField(name string, value ent.Value) error {
	switch name {
	case station.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case station.FieldStatus:
		v, ok := value.(station.Status)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case station.FieldCheckoutTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCheckoutTime(v)
		return nil
	case station.FieldCurrentPlayer:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCurrentPlayer(v)
		return nil
	}
	return fmt.Errorf("unknown Station field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *StationMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *StationMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *StationMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Station numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *StationMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(station.FieldCheckoutTime) {
		fields = append(fields, station.FieldCheckoutTime)
	}
	if m.FieldCleared(station.FieldCurrentPlayer) {
		fields = append(fields, station.FieldCurrentPlayer)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *StationMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *StationMutation) ClearField(name string) error {
	switch name {
	case station.FieldCheckoutTime:
		m.ClearCheckoutTime()
		return nil
	case station.FieldCurrentPlayer:
		m.ClearCurrentPlayer()
		return nil
	}
	return fmt.Errorf("unknown Station nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *StationMutation) ResetField(name string) error {
	switch name {
	case station.FieldName:
		m.ResetName()
		return nil
	case station.FieldStatus:
		m.ResetStatus()
		return nil
	case station.FieldCheckoutTime:
		m.ResetCheckoutTime()
		return nil
	case station.FieldCurrentPlayer:
		m.ResetCurrentPlayer()
		return nil
	}
	return fmt.Errorf("unknown Station field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *StationMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *StationMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *StationMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *StationMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *StationMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *StationMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *StationMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Station unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *StationMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Station edge %s", name)
}
