// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/cobbleopolis/dragoncontimer/ent/schema"
	"github.com/cobbleopolis/dragoncontimer/ent/station"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	stationFields := schema.Station{}.Fields()
	_ = stationFields
	// stationDescID is the schema descriptor for id field.
	stationDescID := stationFields[0].Descriptor()
	// station.DefaultID holds the default value on creation for the id field.
	station.DefaultID = stationDescID.Default.(func() uuid.UUID)
}
