// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/cobbleopolis/dragoncontimer/ent/station"
	"github.com/google/uuid"
)

// Station is the model entity for the Station schema.
type Station struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Status holds the value of the "status" field.
	Status station.Status `json:"status,omitempty"`
	// CheckoutTime holds the value of the "checkoutTime" field.
	CheckoutTime *time.Time `json:"checkoutTime,omitempty"`
	// CurrentPlayer holds the value of the "currentPlayer" field.
	CurrentPlayer *string `json:"currentPlayer,omitempty"`
	// OrderPriority holds the value of the "orderPriority" field.
	OrderPriority int `json:"orderPriority,omitempty"`
	selectValues  sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Station) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case station.FieldOrderPriority:
			values[i] = new(sql.NullInt64)
		case station.FieldName, station.FieldStatus, station.FieldCurrentPlayer:
			values[i] = new(sql.NullString)
		case station.FieldCheckoutTime:
			values[i] = new(sql.NullTime)
		case station.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Station fields.
func (_m *Station) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case station.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case station.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case station.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = station.Status(value.String)
			}
		case station.FieldCheckoutTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field checkoutTime", values[i])
			} else if value.Valid {
				_m.CheckoutTime = new(time.Time)
				*_m.CheckoutTime = value.Time
			}
		case station.FieldCurrentPlayer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currentPlayer", values[i])
			} else if value.Valid {
				_m.CurrentPlayer = new(string)
				*_m.CurrentPlayer = value.String
			}
		case station.FieldOrderPriority:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field orderPriority", values[i])
			} else if value.Valid {
				_m.OrderPriority = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Station.
// This includes values selected through modifiers, order, etc.
func (_m *Station) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Station.
// Note that you need to call Station.Unwrap() before calling this method if this Station
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Station) Update() *StationUpdateOne {
	return NewStationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Station entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Station) Unwrap() *Station {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Station is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Station) String() string {
	var builder strings.Builder
	builder.WriteString("Station(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.CheckoutTime; v != nil {
		builder.WriteString("checkoutTime=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CurrentPlayer; v != nil {
		builder.WriteString("currentPlayer=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("orderPriority=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrderPriority))
	builder.WriteByte(')')
	return builder.String()
}

// Stations is a parsable slice of Station.
type Stations []*Station
