// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cobbleopolis/dragoncontimer/ent/station"
	"github.com/google/uuid"
)

// StationCreate is the builder for creating a Station entity.
type StationCreate struct {
	config
	mutation *StationMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *StationCreate) SetName(v string) *StationCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *StationCreate) SetStatus(v station.Status) *StationCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *StationCreate) SetNillableStatus(v *station.Status) *StationCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCheckoutTime sets the "checkoutTime" field.
func (_c *StationCreate) SetCheckoutTime(v time.Time) *StationCreate {
	_c.mutation.SetCheckoutTime(v)
	return _c
}

// SetNillableCheckoutTime sets the "checkoutTime" field if the given value is not nil.
func (_c *StationCreate) SetNillableCheckoutTime(v *time.Time) *StationCreate {
	if v != nil {
		_c.SetCheckoutTime(*v)
	}
	return _c
}

// SetCurrentPlayer sets the "currentPlayer" field.
func (_c *StationCreate) SetCurrentPlayer(v string) *StationCreate {
	_c.mutation.SetCurrentPlayer(v)
	return _c
}

// SetNillableCurrentPlayer sets the "currentPlayer" field if the given value is not nil.
func (_c *StationCreate) SetNillableCurrentPlayer(v *string) *StationCreate {
	if v != nil {
		_c.SetCurrentPlayer(*v)
	}
	return _c
}

// SetOrderPriority sets the "orderPriority" field.
func (_c *StationCreate) SetOrderPriority(v int) *StationCreate {
	_c.mutation.SetOrderPriority(v)
	return _c
}

// SetNillableOrderPriority sets the "orderPriority" field if the given value is not nil.
func (_c *StationCreate) SetNillableOrderPriority(v *int) *StationCreate {
	if v != nil {
		_c.SetOrderPriority(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *StationCreate) SetID(v uuid.UUID) *StationCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *StationCreate) SetNillableID(v *uuid.UUID) *StationCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the StationMutation object of the builder.
func (_c *StationCreate) Mutation() *StationMutation {
	return _c.mutation
}

// Save creates the Station in the database.
func (_c *StationCreate) Save(ctx context.Context) (*Station, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *StationCreate) SaveX(ctx context.Context) *Station {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *StationCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := station.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.OrderPriority(); !ok {
		v := station.DefaultOrderPriority
		_c.mutation.SetOrderPriority(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := station.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *StationCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Station.name"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Station.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := station.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Station.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OrderPriority(); !ok {
		return &ValidationError{Name: "orderPriority", err: errors.New(`ent: missing required field "Station.orderPriority"`)}
	}
	return nil
}

func (_c *StationCreate) sqlSave(ctx context.Context) (*Station, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *StationCreate) createSpec() (*Station, *sqlgraph.CreateSpec) {
	var (
		_node = &Station{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(station.Table, sqlgraph.NewFieldSpec(station.FieldID, field.TypeUUID))
	)
	_spec.Schema = _c.schemaConfig.Station
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(station.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(station.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CheckoutTime(); ok {
		_spec.SetField(station.FieldCheckoutTime, field.TypeTime, value)
		_node.CheckoutTime = &value
	}
	if value, ok := _c.mutation.CurrentPlayer(); ok {
		_spec.SetField(station.FieldCurrentPlayer, field.TypeString, value)
		_node.CurrentPlayer = &value
	}
	if value, ok := _c.mutation.OrderPriority(); ok {
		_spec.SetField(station.FieldOrderPriority, field.TypeInt, value)
		_node.OrderPriority = value
	}
	return _node, _spec
}

// StationCreateBulk is the builder for creating many Station entities in bulk.
type StationCreateBulk struct {
	config
	err      error
	builders []*StationCreate
}

// Save creates the Station entities in the database.
func (_c *StationCreateBulk) Save(ctx context.Context) ([]*Station, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Station, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *StationCreateBulk) SaveX(ctx context.Context) []*Station {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
