// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cobbleopolis/dragoncontimer/ent/internal"
	"github.com/cobbleopolis/dragoncontimer/ent/predicate"
	"github.com/cobbleopolis/dragoncontimer/ent/station"
)

// StationUpdate is the builder for updating Station entities.
type StationUpdate struct {
	config
	hooks    []Hook
	mutation *StationMutation
}

// Where appends a list predicates to the StationUpdate builder.
func (_u *StationUpdate) Where(ps ...predicate.Station) *StationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *StationUpdate) SetName(v string) *StationUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *StationUpdate) SetNillableName(v *string) *StationUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *StationUpdate) SetStatus(v station.Status) *StationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *StationUpdate) SetNillableStatus(v *station.Status) *StationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCheckoutTime sets the "checkoutTime" field.
func (_u *StationUpdate) SetCheckoutTime(v time.Time) *StationUpdate {
	_u.mutation.SetCheckoutTime(v)
	return _u
}

// SetNillableCheckoutTime sets the "checkoutTime" field if the given value is not nil.
func (_u *StationUpdate) SetNillableCheckoutTime(v *time.Time) *StationUpdate {
	if v != nil {
		_u.SetCheckoutTime(*v)
	}
	return _u
}

// ClearCheckoutTime clears the value of the "checkoutTime" field.
func (_u *StationUpdate) ClearCheckoutTime() *StationUpdate {
	_u.mutation.ClearCheckoutTime()
	return _u
}

// SetCurrentPlayer sets the "currentPlayer" field.
func (_u *StationUpdate) SetCurrentPlayer(v string) *StationUpdate {
	_u.mutation.SetCurrentPlayer(v)
	return _u
}

// SetNillableCurrentPlayer sets the "currentPlayer" field if the given value is not nil.
func (_u *StationUpdate) SetNillableCurrentPlayer(v *string) *StationUpdate {
	if v != nil {
		_u.SetCurrentPlayer(*v)
	}
	return _u
}

// ClearCurrentPlayer clears the value of the "currentPlayer" field.
func (_u *StationUpdate) ClearCurrentPlayer() *StationUpdate {
	_u.mutation.ClearCurrentPlayer()
	return _u
}

// Mutation returns the StationMutation object of the builder.
func (_u *StationUpdate) Mutation() *StationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StationUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := station.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Station.status": %w`, err)}
		}
	}
	return nil
}

func (_u *StationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(station.Table, station.Columns, sqlgraph.NewFieldSpec(station.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(station.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(station.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CheckoutTime(); ok {
		_spec.SetField(station.FieldCheckoutTime, field.TypeTime, value)
	}
	if _u.mutation.CheckoutTimeCleared() {
		_spec.ClearField(station.FieldCheckoutTime, field.TypeTime)
	}
	if value, ok := _u.mutation.CurrentPlayer(); ok {
		_spec.SetField(station.FieldCurrentPlayer, field.TypeString, value)
	}
	if _u.mutation.CurrentPlayerCleared() {
		_spec.ClearField(station.FieldCurrentPlayer, field.TypeString)
	}
	_spec.Node.Schema = _u.schemaConfig.Station
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{station.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StationUpdateOne is the builder for updating a single Station entity.
type StationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StationMutation
}

// SetName sets the "name" field.
func (_u *StationUpdateOne) SetName(v string) *StationUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *StationUpdateOne) SetNillableName(v *string) *StationUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *StationUpdateOne) SetStatus(v station.Status) *StationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *StationUpdateOne) SetNillableStatus(v *station.Status) *StationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCheckoutTime sets the "checkoutTime" field.
func (_u *StationUpdateOne) SetCheckoutTime(v time.Time) *StationUpdateOne {
	_u.mutation.SetCheckoutTime(v)
	return _u
}

// SetNillableCheckoutTime sets the "checkoutTime" field if the given value is not nil.
func (_u *StationUpdateOne) SetNillableCheckoutTime(v *time.Time) *StationUpdateOne {
	if v != nil {
		_u.SetCheckoutTime(*v)
	}
	return _u
}

// ClearCheckoutTime clears the value of the "checkoutTime" field.
func (_u *StationUpdateOne) ClearCheckoutTime() *StationUpdateOne {
	_u.mutation.ClearCheckoutTime()
	return _u
}

// SetCurrentPlayer sets the "currentPlayer" field.
func (_u *StationUpdateOne) SetCurrentPlayer(v string) *StationUpdateOne {
	_u.mutation.SetCurrentPlayer(v)
	return _u
}

// SetNillableCurrentPlayer sets the "currentPlayer" field if the given value is not nil.
func (_u *StationUpdateOne) SetNillableCurrentPlayer(v *string) *StationUpdateOne {
	if v != nil {
		_u.SetCurrentPlayer(*v)
	}
	return _u
}

// ClearCurrentPlayer clears the value of the "currentPlayer" field.
func (_u *StationUpdateOne) ClearCurrentPlayer() *StationUpdateOne {
	_u.mutation.ClearCurrentPlayer()
	return _u
}

// Mutation returns the StationMutation object of the builder.
func (_u *StationUpdateOne) Mutation() *StationMutation {
	return _u.mutation
}

// Where appends a list predicates to the StationUpdate builder.
func (_u *StationUpdateOne) Where(ps ...predicate.Station) *StationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StationUpdateOne) Select(field string, fields ...string) *StationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Station entity.
func (_u *StationUpdateOne) Save(ctx context.Context) (*Station, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StationUpdateOne) SaveX(ctx context.Context) *Station {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StationUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := station.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Station.status": %w`, err)}
		}
	}
	return nil
}

func (_u *StationUpdateOne) sqlSave(ctx context.Context) (_node *Station, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(station.Table, station.Columns, sqlgraph.NewFieldSpec(station.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Station.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, station.FieldID)
		for _, f := range fields {
			if !station.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != station.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(station.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(station.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CheckoutTime(); ok {
		_spec.SetField(station.FieldCheckoutTime, field.TypeTime, value)
	}
	if _u.mutation.CheckoutTimeCleared() {
		_spec.ClearField(station.FieldCheckoutTime, field.TypeTime)
	}
	if value, ok := _u.mutation.CurrentPlayer(); ok {
		_spec.SetField(station.FieldCurrentPlayer, field.TypeString, value)
	}
	if _u.mutation.CurrentPlayerCleared() {
		_spec.ClearField(station.FieldCurrentPlayer, field.TypeString)
	}
	_spec.Node.Schema = _u.schemaConfig.Station
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &Station{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{station.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
