// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// Station is the predicate function for station builders.
type Station func(*sql.Selector)
